/**
 * Shared cup config. Kept out of the scene file so the light wrapper can read
 * variant sizing without dragging three.js into its chunk.
 */

// Content-hashed filename, regenerated by scripts/build-cup-model.js.
export { CUP_MODEL_URL } from './model';

export type CupVariant = 'showcase' | 'spot';

interface CupConfig {
  /** Camera distance on Z. Model is 2 units tall, centred on the origin. */
  camera: number;
  scale: number;
  /** Nudges the cup within the frame so the lid doesn't crowd the top edge. */
  yOffset: number;
  /** Max pointer tilt in radians. */
  tilt: number;
  secondsPerTurn: number;
  shadowY: number;
  shadowOpacity: number;
  /** CSS min-height for the reserved box, so layout never jumps on load. */
  minHeight: number;
}

/**
 * Framing. scripts/build-cup-model.js emits the cup centred on the origin with
 * bounds x ±0.710, y ±1.0, z ±0.710, so its silhouette half-width as it spins is
 * the XZ radius sqrt(0.710² + 0.710²) ≈ 1.0 - frame against that, not against
 * half-width alone, or an edge clips through part of every turn.
 *
 * Visible half-height at the model is tan(fov/2) * camera, and half-width is that
 * times the container's aspect ratio. Both boxes below are portrait, so width is
 * the binding constraint even though the cup is taller than it is wide. Pointer
 * tilt costs a little more of both (radius * sin θ), which is why the margins
 * look generous.
 */
export const VARIANTS: Record<CupVariant, CupConfig> = {
  // Footer hero cup: large, slow, responds to the pointer.
  showcase: {
    camera: 6.6,
    scale: 1.3,
    yOffset: 0,
    tilt: 0.14,
    secondsPerTurn: 24,
    shadowY: -1.33,
    shadowOpacity: 0.22,
    minHeight: 200,
  },
  // Inline accent (empty cart, confirmations): smaller, faster, decorative only.
  spot: {
    camera: 5.6,
    scale: 1.3,
    yOffset: 0,
    tilt: 0.09,
    secondsPerTurn: 18,
    shadowY: -1.33,
    shadowOpacity: 0.16,
    minHeight: 132,
  },
};
