/**
 * Shared cup config. Kept out of the scene file so the light wrapper can read
 * variant sizing without dragging three.js into its chunk.
 */

// Content-hashed filename, regenerated by scripts/build-cup-model.js.
export { CUP_MODEL_URL } from './model';

export type CupVariant = 'showcase' | 'spot' | 'favicon';

interface CupConfig {
  /** Camera distance on Z. Model is 2 units tall, centred on the origin. */
  camera: number;
  scale: number;
  /** Nudges the cup within the frame so the lid doesn't crowd the top edge. */
  yOffset: number;
  /** Max pointer tilt in radians. */
  tilt: number;
  /** Seconds for a full turn, or for one back-and-forth swing when `sway` is set. */
  secondsPerTurn: number;
  /**
   * Swing this far either side of the front face instead of turning all the way
   * round. The sleeve's wordmark only spans about 100 degrees of the cup, so a
   * full turn spends most of it edge-on or facing away, which reads as a cropped
   * logo. Rotation 0 puts a wordmark square to the camera (the lathe maps u=0.75
   * of the texture, one of the two wordmark centres, to +Z), so a small swing
   * keeps it readable the whole time.
   */
  sway?: number;
  shadowY: number;
  shadowOpacity: number;
  /** CSS min-height for the reserved box, so layout never jumps on load. */
  minHeight: number;
}

/**
 * Framing. scripts/build-cup-model.js emits the cup centred on the origin with
 * bounds x ±0.710, y ±1.0, z ±0.710, so its silhouette half-width as it spins is
 * the XZ radius sqrt(0.710² + 0.710²) ≈ 1.0 - frame against that, not against
 * half-width alone, or an edge clips through part of every turn.
 *
 * Visible half-height at the model is tan(fov/2) * camera, and half-width is that
 * times the container's aspect ratio. Both boxes below are portrait, so width is
 * the binding constraint even though the cup is taller than it is wide. Pointer
 * tilt costs a little more of both (radius * sin θ), which is why the margins
 * look generous.
 */
export const VARIANTS: Record<CupVariant, CupConfig> = {
  // Footer hero cup: large, slow, responds to the pointer.
  showcase: {
    camera: 6.6,
    scale: 1.3,
    yOffset: 0,
    tilt: 0.14,
    secondsPerTurn: 24,
    shadowY: -1.33,
    shadowOpacity: 0.22,
    minHeight: 200,
  },
  // Inline accent (empty cart, confirmations): smaller, faster, decorative only.
  spot: {
    camera: 6.4,
    scale: 1.3,
    yOffset: 0.08,
    tilt: 0.09,
    secondsPerTurn: 18,
    sway: 0.1,
    shadowY: -1.33,
    shadowOpacity: 0.16,
    minHeight: 132,
  },
  // Browser-tab icon: tiny, no shadow (invisible at that size), spins fast enough
  // to read as motion even though it's only sampled a few times a second.
  favicon: {
    camera: 5.6,
    scale: 1.3,
    yOffset: 0,
    tilt: 0,
    secondsPerTurn: 7,
    shadowY: -1.33,
    shadowOpacity: 0,
    minHeight: 48,
  },
};
