// Generated by scripts/build-cup-model.js - do not edit.
// Filename is content-hashed, so a rebuilt cup can never be shadowed by a
// cached copy of an older one. Run `npm run build:cup` to regenerate.
export const CUP_MODEL_URL = '/models/grabbit-cup.c5d5c0c9.glb';
